@TodoList_HostAddress = http://localhost:5272

GET {{TodoList_HostAddress}}/todo/
Accept: application/json

###

GET {{TodoList_HostAddress}}/todo/1
Accept: application/json

###

GET {{TodoList_HostAddress}}/todo/7
Accept: application/json

###

POST {{TodoList_HostAddress}}/todo
Content-Type: application/json

{
    "conteudo": "Hidratar o cabelo",
    "estaFeita": false
}

###

PUT {{TodoList_HostAddress}}/todo/4
Content-Type: application/json

{
    "id": 4,
    "conteudo": "Lavar e hidratar o cabelo",
    "estaFeita": false
}

###

DELETE {{TodoList_HostAddress}}/todo/4
